### ISSUE TITLE
Export vars like normal ClojureScript, using :export metadata

### ISSUE THREAD

**Issue by divs1210** [borkdude/scittle#7]
```clojure
(defn my-alert []
  (js/alert "You clicked!"))

;; export function to use from JavaScript:
(set! (.-my_alert js/window) my-alert)
```
might be better expressed as:
```clojure
(defn ^:export my-alert []
  (js/alert "You clicked!"))
```

In the likely case that you have already considered this, I would like to know if there's any blockers preventing this.

**Comment by borkdude** [comment]
I had implemented it like that before, but this requires either patching the `defn` macro or walking all newly created vars (performance). So I went for this explicit way of exporting right now.

**Comment by divs1210** [comment]
Makes sense.

Why is this exporting mechanism required, though?

Why doesn't defining a function `f` inside namespace `n` make the function `n.f()` callable from JS?

**Comment by borkdude** [comment]
Because sci keeps its environment encapsulated from the outside world. Creating vars, namespaces, etc does not affect the host runtime.

**Comment by divs1210** [comment]
Got it, thanks!

This is a nifty little library!

Unrelated: could you explain why reagent needs to be wrapped to be used from SCI, and how to wrap other CLJS libs?

**Comment by borkdude** [comment]
@divs1210 Two reasons

1) You need to explicitly provide functions which sci can access, since it doesn't access what it isn't allowed to access
2) Advanced CLJS compilation requires you to preserve these functions so you need to hold on to them somewhere.

The sci configuration accomplishes both 1 and 2.

Because scittle is compiled with advanced compilation, plugins need to be based of off the same code-base. So to create a plugin you can make an issue (and after some discussion a PR) or fork this repository and make your own assortment of plugins.

Another option would be to offer an additional non-advanced compiled version of scittle, so it would be open for extension by third parties outside of this repo. But this would also mean that the JS would be around 5mb (probably less than 1mb gzipped) instead of 600kb (138kb  gzipped).

**Comment by divs1210** [comment]
Thanks! 🙏🏼

If I understand correctly, a mechanism for exposing third party libraries to scittle (like babashka pods for babashka) could be developed which wouldn't require maintaining a fork of scittle?

**Comment by borkdude** [comment]
@divs1210 Correct, that can work and that has crossed my mind. Here are my thoughts on that:  

If you write a scittle pod in CLJS, then each pod would bring their own advanced compiled version of the CLJS data structures etc, which wouldn't be so efficient, unless you implement them in pure JS. But if you would implement them in pure JS, then offering it as a pod doesn't have huge benefits either, since you can just use JS interop to access those functions.

**Comment by divs1210** [comment]
Hmm, so the most practical way to use scittle would be to use scittle + JS libs.

This makes a lot of sense.

Scittle is great to make quick webpages with Clojure scripting enabled and the added goodness of reagent.

Larger projects would warrant using full-fledged CLJS anyway.

Thanks for taking the time, and thanks for Scittle! 🙏🏼

**Comment by borkdude** [comment]
Forgot to mention. If you have a small set of custom CLJS that you would like to expose you can also do that using the script tag.

**Comment by borkdude** [comment]
But yes, that is the sweet spot for scittle. For bigger projects, just go with the normal CLJS project setup.
